# -*- coding: utf-8 -*-
"""
Created on Fri Oct 14 13:57:32 2022

@author: Naveen Kumar
"""

import pandas as pd
import networkx as nx 

# Load the dataset
G = pd.read_csv(r"C:\Users\Naveen Kumar\Desktop\Data Science\Assignments\DataSets\instagram.csv")


g = nx.Graph()
g1 = nx.from_pandas_edgelist(G, source = '1', target = '2')
g2 = nx.from_pandas_edgelist(G, source = '1', target = '3')
g3 = nx.from_pandas_edgelist(G, source = '1', target = '4')
g4 = nx.from_pandas_edgelist(G, source = '1', target = '5')
g5 = nx.from_pandas_edgelist(G, source = '1', target = '6')
g6 = nx.from_pandas_edgelist(G, source = '1', target = '7')
g7 = nx.from_pandas_edgelist(G, source = '1', target = '8')
#g8 = nx.from_pandas_edgelist(G, source = '1', target = '9')
g9 = nx.from_pandas_edgelist(G, source = '2', target = '3')
g10 = nx.from_pandas_edgelist(G, source = '2', target = '4')
g11 = nx.from_pandas_edgelist(G, source = '2', target = '5')
g12 = nx.from_pandas_edgelist(G, source = '2', target = '6')
g13 = nx.from_pandas_edgelist(G, source = '2', target = '7')
g14 = nx.from_pandas_edgelist(G, source = '2', target = '8')
#g15 = nx.from_pandas_edgelist(G, source = '2', target = '9')
g16 = nx.from_pandas_edgelist(G, source = '3', target = '4')
g17 = nx.from_pandas_edgelist(G, source = '3', target = '5')
g18 = nx.from_pandas_edgelist(G, source = '3', target = '6')
g19 = nx.from_pandas_edgelist(G, source = '3', target = '7')
g20 = nx.from_pandas_edgelist(G, source = '3', target = '8')
#g21 = nx.from_pandas_edgelist(G, source = '3', target = '9')
g22 = nx.from_pandas_edgelist(G, source = '4', target = '5')
g23 = nx.from_pandas_edgelist(G, source = '4', target = '6')
g24 = nx.from_pandas_edgelist(G, source = '4', target = '7')
g25 = nx.from_pandas_edgelist(G, source = '4', target = '8')
#g26 = nx.from_pandas_edgelist(G, source = '4', target = '9')
g27 = nx.from_pandas_edgelist(G, source = '5', target = '6')
g28 = nx.from_pandas_edgelist(G, source = '5', target = '7')
g29 = nx.from_pandas_edgelist(G, source = '5', target = '8')
#g30 = nx.from_pandas_edgelist(G, source = '5', target = '9')
g31 = nx.from_pandas_edgelist(G, source = '6', target = '7')
g32 = nx.from_pandas_edgelist(G, source = '6', target = '8')
#g33 = nx.from_pandas_edgelist(G, source = '6', target = '9')
g34 = nx.from_pandas_edgelist(G, source = '7', target = '8')
#g35 = nx.from_pandas_edgelist(G, source = '7', target = '9')
#g36 = nx.from_pandas_edgelist(G, source = '8', target = '9')

print(nx.info(g1))

pos1 = nx.spring_layout(g1)
pos2 = nx.spring_layout(g2)
pos3 = nx.spring_layout(g3)
pos4 = nx.spring_layout(g4)
pos5 = nx.spring_layout(g5)
pos6 = nx.spring_layout(g6)
pos7 = nx.spring_layout(g7)
#pos8 = nx.spring_layout(g8)
pos9 = nx.spring_layout(g9)
pos10 = nx.spring_layout(g10)
pos11 = nx.spring_layout(g11)
pos12 = nx.spring_layout(g12)
pos13 = nx.spring_layout(g13)
pos14 = nx.spring_layout(g14)
#pos15 = nx.spring_layout(g15)
pos16 = nx.spring_layout(g16)
pos17 = nx.spring_layout(g17)
pos18 = nx.spring_layout(g18)
pos19 = nx.spring_layout(g19)
pos20 = nx.spring_layout(g20)
#pos21 = nx.spring_layout(g21)
pos22 = nx.spring_layout(g22)
pos23 = nx.spring_layout(g23)
pos24 = nx.spring_layout(g24)
pos25 = nx.spring_layout(g25)
#pos26 = nx.spring_layout(g26)
pos27 = nx.spring_layout(g27)
pos28 = nx.spring_layout(g28)
pos29 = nx.spring_layout(g29)
#pos30 = nx.spring_layout(g30)
pos31 = nx.spring_layout(g31)
pos32 = nx.spring_layout(g32)
#pos33 = nx.spring_layout(g33)
pos34 = nx.spring_layout(g34)
#pos35 = nx.spring_layout(g35)
#pos36 = nx.spring_layout(g36)

nx.draw_networkx(g1, pos1, node_size = 15, node_color = 'red')
nx.draw_networkx(g2, pos2, node_size = 15, node_color = 'red')
nx.draw_networkx(g3, pos3, node_size = 15, node_color = 'red')
nx.draw_networkx(g4, pos4, node_size = 15, node_color = 'red')
nx.draw_networkx(g5, pos5, node_size = 15, node_color = 'red')
nx.draw_networkx(g6, pos6, node_size = 15, node_color = 'red')
nx.draw_networkx(g7, pos7, node_size = 15, node_color = 'red')
#nx.draw_networkx(g8, pos8, node_size = 15, node_color = 'red')
nx.draw_networkx(g9, pos9, node_size = 15, node_color = 'red')
nx.draw_networkx(g10, pos10, node_size = 15, node_color = 'red')
nx.draw_networkx(g11, pos11, node_size = 15, node_color = 'red')
nx.draw_networkx(g12, pos12, node_size = 15, node_color = 'red')
nx.draw_networkx(g13, pos13, node_size = 15, node_color = 'red')
nx.draw_networkx(g14, pos14, node_size = 15, node_color = 'red')
#nx.draw_networkx(g15, pos15, node_size = 15, node_color = 'red')
nx.draw_networkx(g16, pos16, node_size = 15, node_color = 'red')
nx.draw_networkx(g17, pos17, node_size = 15, node_color = 'red')
nx.draw_networkx(g18, pos18, node_size = 15, node_color = 'red')
nx.draw_networkx(g19, pos19, node_size = 15, node_color = 'red')
nx.draw_networkx(g20, pos20, node_size = 15, node_color = 'red')
#nx.draw_networkx(g21, pos21, node_size = 15, node_color = 'red')
nx.draw_networkx(g22, pos22, node_size = 15, node_color = 'red')
nx.draw_networkx(g23, pos23, node_size = 15, node_color = 'red')
nx.draw_networkx(g24, pos24, node_size = 15, node_color = 'red')
nx.draw_networkx(g25, pos25, node_size = 15, node_color = 'red')
#nx.draw_networkx(g26, pos26, node_size = 15, node_color = 'red')
nx.draw_networkx(g27, pos27, node_size = 15, node_color = 'red')
nx.draw_networkx(g28, pos28, node_size = 15, node_color = 'red')
nx.draw_networkx(g29, pos29, node_size = 15, node_color = 'red')
#nx.draw_networkx(g30, pos30, node_size = 15, node_color = 'red')
nx.draw_networkx(g31, pos31, node_size = 15, node_color = 'red')
nx.draw_networkx(g32, pos32, node_size = 15, node_color = 'red')
#nx.draw_networkx(g33, pos33, node_size = 15, node_color = 'red')
nx.draw_networkx(g34, pos34, node_size = 15, node_color = 'red')
#nx.draw_networkx(g35, pos35, node_size = 15, node_color = 'red')
#nx.draw_networkx(g36, pos36, node_size = 15, node_color = 'red')
